import torch
from transformers import  BartForConditionalGeneration, BartTokenizer

model_name =  "facebook/bart-large-cnn"
tokenizer = BartTokenizer.from_pretrained(model_name)
model = BartForConditionalGeneration.from_pretrained(model_name)
def summerization(text , max_len , min_len):
  input = tokenizer(text , return_tensors = "pt" , max_length=max_len , truncation=True , padding= True)
  summary_idx = model.generate(input["input_ids"] , min_length = min_len , max_length = max_len , do_sample = False)
  summary = tokenizer.decode(summary_idx[0] , skip_special_tokens= True)
  return summary
text = """An interrupt is a signal generated by a hardware device
to get CPU attention. Interrupt transfers control to the
interrupt service routine ISR generally through the
interrupt vector table which contains addresses of all
service routines. The interrupt service routine executes
and on completion the CPU resumes the interrupted
computation. Interrupt architecture must save the address
of the interrupted instruction. Incoming interrupts are
disabled while another interrupt is being processed to
prevent a lost interrupt. An operating system is an
interrupt driven software. A trap or exception is a
software generated interrupt caused by an error like
division by zero or invalid memory access or by a user
request for an operating system service. A signal is an
event generated to get attention of a process."""
summerize = summerization(text , max_len = 70 , min_len =30  )
print(summerize)
print(len(summerize.split()))
print(len(text.split()))
